version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoparts_app
    ports:
      - "8080:80"  # Изменил порт, чтобы не конфликтовать с phpMyAdmin
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      # Подключение к существующему MySQL контейнеру
      DB_HOST: my_mysql_container  # Имя контейнера MySQL
      DB_PORT: 3306
      DB_NAME: danchous
      DB_USER: danchous
      DB_PASS: danchous
      SITE_URL: http://localhost:8080/autoparts
    restart: unless-stopped
    networks:
      - autoparts_network
    depends_on:
      - mysql_db

  # Подключаем существующую БД к той же сети
  mysql_db:
    image: mysql:8.0
    container_name: my_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: danchous
      MYSQL_DATABASE: danchous
      MYSQL_USER: danchous
      MYSQL_PASSWORD: danchous
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - autoparts_network

  phpmyadmin_panel:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin_panel
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: my_mysql_container
      PMA_PORT: 3306
    networks:
      - autoparts_network
    depends_on:
      - mysql_db

networks:
  autoparts_network:
    driver: bridge

volumes:
  mysql_data: {}
